output "cce_cluster" {
  value       = opentelekomcloud_cce_cluster_v3.cluster
  description = <<DESCRIPTION
Use this data source to get details about all clusters and obtains the certificate for accessing cluster information

* `id` - ID of the cluster resource.
* `status` - Cluster status information.
* `internal` - The internal network address.
* `external` - The external network address.
* `external_otc` - The endpoint of the cluster to be accessed through API Gateway.
* `certificate_clusters/name` - The cluster name.
* `certificate_clusters/server` - The server IP address.
* `certificate_clusters/certificate_authority_data` - The certificate data.
* `certificate_users/name` - The user name.
* `certificate_users/client_certificate_data` - The client certificate data.
* `certificate_users/client_key_data` - The client key data.
* `installed_addons` - List of installed addon IDs. Empty if `ignore_addons` is `true`.
* `security_group_control` - ID of the autogenerated security group for the CCE master port.
* `security_group_node` - ID of the autogenerated security group for the CCE nodes.

Example output:
```
output "cluster_id" {
  value = module.module_name.cce_cluster.id
}
```
DESCRIPTION
}

output "node_pool" {
  value       = opentelekomcloud_cce_node_pool_v3.this
  description = <<DESCRIPTION
Use this data source to get the specified node in a cluster from OpenTelekomCloud

* `status` - Node status information.
* `id` - Specifies a resource ID in UUID format.

Example output:
```
output = "node_pool_id" {
  value = module.module_name.node_pool.id
}
```
DESCRIPTION
}

output "cce_node" {
  value       = opentelekomcloud_cce_node_v3.this
  description = <<DESCRIPTION
Use this data source to get the specified node in a cluster from OpenTelekomCloud

* `status` - Node status information.
* `server_id` - ID of the ECS where the node resides.
* `public_ip` - Public IP of the CCE node.

Example output:
```
output "node_status" {
  value = module.module_name.cce_node.status
}
```
DESCRIPTION
}

output "cce_addon" {
  value       = opentelekomcloud_cce_addon_v3.this
  description = <<DESCRIPTION
Use this data source to get from OpenTelekomCloud a CCE Addon template information.

* `name` - Installed add-on name.
* `description` - Installed add-on description

Example output:
```
output "addon_name" {
  value = module.module_name.cce_addon.name
}
```
DESCRIPTION
}
